######################################################################
# Automatically generated by qmake (2.01a) czw. kwi 7 09:23:40 2011
######################################################################

TEMPLATE = app
QT += network
QT -= gui
TARGET = jpks
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cxx
