######################################################################
# Automatically generated by qmake (2.01a) czw. kwi 7 17:24:40 2011
######################################################################

TEMPLATE = app
QT += network
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ControlPanel.hxx
FORMS += ControlPanel.ui
SOURCES += ControlPanel.cxx main.cxx
