######################################################################
# Automatically generated by qmake (2.01a) niedz. kwi 10 13:08:06 2011
######################################################################

TEMPLATE = app
QT += network
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ControlPanel.hxx queue.hxx
FORMS += ControlPanel.ui
SOURCES += ControlPanel.cxx main.cxx queue.cxx
